package com.liliya.quiz.model;

import java.util.Map;

/**
 * A class used to create new quiz objects
 * The objects will contain the list of questions for each quiz game set up on the server
 */
public interface Quiz {


    /**
     * Method returns the name of the quiz
     *
     * @return quiz name
     */
    public String getQuizName();

    /**
     * Specifies the name of the quiz
     *
     * @param name
     */
    public void setQuizName(String name);

    /**
     * Returns the id of the quiz generated by the set up client
     *
     * @return id of the quiz
     */
    public int getQuizId();

    /**
     * Not creating a set quiz id yet as this will be generated automatically by the server
     * when new quiz is created
     */

    /**
     * Gets the quiz questions
     *
     * @return map of questions with id
     */
    public Map<Integer, Question> getQuizQuestions();

    /**
     * Returns true is the quiz is active and false if closed
     * Used to determine if quiz is available for users to play
     *
     * @return
     */
    public boolean getQuizState();

    /**
     * sets the state of the quiz to active or inactive
     *
     * @param state
     */
    public void setQuizState(boolean state);

    /**
     * Returns true or false depending on whether the quiz is set as currently being played
     * @return true or false
     */

    public boolean isQuizPlayed();

    /**
     * Sets the status of the quiz to currently being played; this will help prevent it from being closed too early
     * @param quizPlayed
     */

    public void setQuizPlayed(boolean quizPlayed);
}
