package com.liliya.quiz;

/**
 * A class used to create new quiz objects
 * The objects will contain the list of questions for each quiz game set up on the server
 */
public interface Quiz {


    /**
     * Method returns the name of the quiz
     * @return quiz name
     */
    public String getQuizName();

    /**
     * Specifies the name of the quiz
     * @param name
     */
    public void setQuizName(String name);

    /**
     * Returns the id of the quiz generated by the set up client
     * @return id of the quiz
     */
    public int getQuizId();

    /**
     * Not creating a set quiz id yet as this will be generated automatically by the server
     * when new quiz is created
     */
}
